### ISSUE TITLE
continue option does not work

### ISSUE THREAD

**Issue by alelau** [mgol/check-dependencies#22]
Hi ,

according the documentation in [npmjs](https://www.npmjs.com/package/grunt-check-dependencies)

> // If true, instead of aborting the task after checking (and installing), the task will continue. 
> // Default: `false`. 
> continue: boolean,

i configured the option, but the task is anyway aborted. At the same time I wouldn't use --force.

Regards

**Comment by mgol** [comment]
Can you report it at https://github.com/mgol/grunt-check-dependencies/issues? This is a repo to an underlying package, the `continue` option is defined by the Grunt task.
