### ISSUE TITLE
New package release?

### ISSUE THREAD

**Issue by IceCreamYou** [mgol/check-dependencies#52]
The last release, 1.1.0, was in 2017. There have been quite a few updates since then. Any chance we can get a version bump?

**Comment by flippidippi** [comment]
Same. Just need a publish cause it's updated from dependabot

**Comment by mgol** [comment]
I've just released https://github.com/mgol/check-dependencies/releases/tag/1.1.1 to improve security and https://github.com/mgol/check-dependencies/releases/tag/2.0.0 with some further improvements/refactors/simplifications.

**Comment by flippidippi** [comment]
I ended up building my own since then. It happens to have a lot of the changes you made with 2.0.0 (simplifications, less deps, async/await) 😅 It also does an engines check.

If you wanna check it out: https://gitlab.com/flippidippi/check-installed
