### ISSUE TITLE
`packageDir` is an invalid option despite being documented

### ISSUE THREAD

**Issue by eric-gonzalez-tfs** [mgol/check-dependencies#59]
In the latest version, `packageDir` stopped working despite it being in the documentation.

<img width="802" alt="image" src="https://github.com/mgol/check-dependencies/assets/82120345/4440c351-5f70-4da4-a904-cbebc8dce668">

**Comment by mgol** [comment]
It's `--package-dir`. Previously, both versions worked but I switched parameter parsing to native `util.parseArgs()` in `2.0.0` and it's more strict.

I added info to the release notes about this: https://github.com/mgol/check-dependencies/releases/tag/2.0.0

**Comment by mgol** [comment]
I added more direct info about it to the README in b80a8740a67952cfba01b791078930d0dcb52c72.

**Comment by eric-gonzalez-tfs** [comment]
Thanks for the quick response @mgol! Appreciate the work here.
